---
title: "Datasets in MicrobiomeBenchmarkData"
author:
  - name: "Samuel Gamboa"
    email: "Samuel.Gamboa.Tuz@gmail.com"
output: 
  BiocStyle::html_document:
    toc: true
vignette: >
  %\VignetteIndexEntry{Datasets in MicrobiomeBenchmarkData}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
    collapse = TRUE,
    comment = "#>"
)
```

```{r, echo=FALSE, message=FALSE}
## This code is to import the description of the datasets
## Only the table should be displayed on the vignette
library(MicrobiomeBenchmarkData)
fname <- system.file(
    'extdata/datasets.tsv', package = 'MicrobiomeBenchmarkData'
)
datasets <- read.table(
    fname, header = TRUE, sep = '\t', check.names = FALSE
)
data('sampleMetadata', package = 'MicrobiomeBenchmarkData')
PMID <- dplyr::distinct(
    sampleMetadata[, c('dataset', 'pmid')]
)
datasets <- dplyr::left_join(datasets, PMID, by = c('Dataset' = 'dataset'))
datasets <- dplyr::rename(datasets, PMID = pmid)
```

In the table below, you can find the collection of datasets currently available
through the MicrobiomeBenchmarkData package. These datasets are also avialable
on Zenodo: https://doi.org/10.5281/zenodo.6911026

```{r, echo=FALSE}
## Show table
knitr::kable(datasets, filter = 'top')
```

```{r, echo=FALSE, include=FALSE}
sessionInfo()
```

