---
title: "MicrobiomeBenchmarkData"
author:
  - name: "Samuel D. Gamboa-Tuz"
    email: "Samuel.Gamboa.Tuz@gmail.com"
  - name: "Levi Waldron"
package: MicrobiomeBenchmarkData
output: 
  BiocStyle::html_document:
    toc: true
abstract: >
  Document summary
vignette: >
  %\VignetteIndexEntry{MicrobiomeBenchmarkData}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# Introduction

# Installation

```{r installation, eval=FALSE}
# if (!"BiocManager" %in% installed.packages()[,"Package"])
  install.packages("BiocManager")

## Release version
# BiocManager::install("MicrobiomeBenchmarkData")

## Latest development version
# BiocManager::install("waldronlab/MicrobiomeBenchmarkData")
```


```{r, load packages}
library(MicrobiomeBenchmarkData)
```

# Accessing datasets

Datasets can be accessed with the `getDatasets` function, which returns a list
of TreeSummarizedExperiments:

```{r}
list_of_datasets <- getDataset()
```

Or can be directly accessed trough the specific dataset function, which
returns a TreeSummarizedExperiment


# Session information

```{r}
sessionInfo()
```

